[package]
name = "evm-abi-decoder"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hyperpipe-sdk = { workspace = true }
wit-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
alloy-primitives = { version = "0.8", default-features = false }
alloy-json-abi = { version = "0.8", default-features = false }
alloy-dyn-abi = { version = "0.8", default-features = false }
